name: example
description: Example
version: 1.3.7+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  selectable_autolink_text:
    path: ../../flutter_selectable_autolink_text
  url_launcher: ^5.4.10
  share: ^0.6.5+4

flutter:
  uses-material-design: true
